## Pointer
指针常用于数组与链表，常见的指针法有**快慢双指针**，**首尾双指针**、**起止双指针**和**滑动窗口**。

[Two Sum II - Input array is sorted](https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/)。给一有序数组与一个目标值，返回和为目标值的两索引。注意，该题索引以$1$为起点，且假设数组中只有一对满足条件的值。

思路：数组已经有序，那么设立首尾双指针。若首尾相加小于target，说明需要加大，则左指针右移；反之右指针左移。

In [ ]:
def twoSum(numbers, target: int):
    left, right = 0, len(numbers)-1

    while left < right:
        cur_sum = numbers[left]+numbers[right]

        if cur_sum == target:
            return [left+1, right+1]
        elif cur_sum < target:
            left += 1
        else:
            right -= 1

[3Sum](https://leetcode.com/problems/3sum/)。给定一数组，找出所有满足a+b+c=0的三元组。

思路：首先对数组排序，然后使用三指针。其中一个指针从左往右固定住一个数字，然后在该数字后面使用首位双指针寻找另外两个数。实际上还是相当于双指针。

In [ ]:
def threeSum(nums):
    n = len(nums)
    nums.sort()
    res = list()

    for idx in range(n-2):
        if idx > 0 and nums[idx] == nums[idx-1]:
            continue

        left, right = idx+1, n-1
        while left < right:
            cur_sum = nums[idx]+nums[left]+nums[right]

            if cur_sum < 0:
                left += 1
            elif cur_sum > 0:
                right -= 1
            else:
                res.append([nums[idx], nums[left], nums[right]])
                left += 1
                right -= 1

                while left < right and nums[left] == nums[left-1]:
                    left += 1
                while left < right and nums[right] == nums[right+1]:
                    right -= 1

    return res

[3Sum Closest](https://leetcode.com/problems/3sum-closest/)。给定一数组与一目标值，求数组中三个数之和最接近目标值的配置。

思路：类似上题，排序，固定首元素，使用双指针去寻找另外两个数字。每次需要计算当前和与目标值的距离，保存最小的。

In [8]:
def threeSumClosest(nums, target: int) -> int:
    res = None
    nums.sort()
    n = len(nums)
    diff = 0x7FFFFFFF

    for idx in range(n-2):
        left, right = idx+1, n-1
        while left < right:
            cur_sum = nums[idx]+nums[left]+nums[right]
            cur_diff = abs(target-cur_sum)
            if cur_diff < diff:
                res = cur_sum
                diff = cur_diff

            if cur_sum < target:
                left += 1
            else:
                right -= 1

    return res

2

[4Sum](https://leetcode.com/problems/4sum/)。给定一数组，找出满足a+b+c+d=sum的所有四元组。

思路：固定前两个数字，后两个数字使用首尾双指针法去寻找。注意跳过重复数字。

In [ ]:
def fourSum(nums, target: int):
    n = len(nums)
    nums.sort()
    res = list()

    for idx_1 in range(n-3):
        if idx_1 > 0 and nums[idx_1] == nums[idx_1-1]:
            continue

        for idx_2 in range(idx_1+1, n-2):
            if idx_2 > (idx_1+1) and nums[idx_2] == nums[idx_2-1]:
                continue

            left, right = idx_2+1, n-1
            while left < right:
                cur_sum = nums[idx_1]+nums[idx_2]+nums[left]+nums[right]
                if cur_sum < target:
                    left += 1
                elif cur_sum > target:
                    right -= 1
                else:
                    res.append([nums[idx_1], nums[idx_2],
                                nums[left], nums[right]])
                    left += 1
                    right -= 1

                    while left < right and nums[left] == nums[left-1]:
                        left += 1
                    while left < right and nums[right] == nums[right+1]:
                        right -= 1

    return res

[Reverse Words in a String III](https://leetcode.com/problems/reverse-words-in-a-string-iii/)。给一句子，反转所有单词。

思路：首先将字符串转成列表便于交换。扫描到第一个非空格字符的位置，记录为```start```，从```start```开始扫描到第一个空格字符的位置，记录为```end```。交换```start```与```end-1```之间的字符。

In [ ]:
def reverseWords(s: str) -> str:
    n = len(s)
    start = 0
    s = list(s)

    def reverse(left, right):
        while left < right:
            s[left], s[right] = s[right], s[left]
            left += 1
            right -= 1

    while start < n:
        # 1. 第一个非空格字符
        while start < n and s[start] == ' ':
            start += 1

        # 2. 第一个空格字符
        end = start
        while end < n and s[end] != ' ':
            end += 1

        # 3. 交换
        reverse(start, end-1)
        start = end

    return ''.join(s)

[Reverse Words in a String](https://leetcode.com/problems/reverse-words-in-a-string/)。给一句子，返回单词逆序的句子，返回字串中不应包含多余的空格。

思路：首先将字串转成列表便于交换。反转整个字串，再反转每个单词。去除空格比较麻烦，首尾空格可以使用```strip()```方法，去除中间的空格可以额外扫描一遍。

In [16]:
def reverseWords(s: str) -> str:
    s = list(s.strip().replace('  ', ' '))
    n = len(s)
    start = 0

    def reverse(left, right):
        while left < right:
            s[left], s[right] = s[right], s[left]
            left += 1
            right -= 1

    reverse(0, n-1)

    while start < n:
        while start < n and s[start] == ' ':
            start += 1

        end = start
        while end < n and s[end] != ' ':
            end += 1

        reverse(start, end-1)
        start = end

    # 去除中间多余的空格
    for idx in range(n-1):
        if s[idx] == ' ' and s[idx+1] == ' ':
            s[idx] = ''

    return ''.join(s)

[Most Common Word](https://leetcode.com/problems/most-common-word/)。给一句子，再给一词表$banned$，找出句子中未在$banned$中出现且频数最高的单词。

思路：找频数最高的单词直接使用哈希表就是弱智题了，该题难点在于在句子中剥离出单词，使用起止双指针法。

In [ ]:
def mostCommonWord(paragraph: str, banned) -> str:
    n = len(paragraph)
    cnts = dict()
    start = 0
    paragraph = paragraph.lower()

    while start < n:
        while start < n and not paragraph[start].isalpha():
            start += 1

        end = start
        while end < n and paragraph[end].isalpha():
            end += 1

        word = paragraph[start:end]
        if word not in banned:
            cnts.setdefault(word, 0)
            cnts[word] += 1

        start = end

    res = None
    max_cnt = 0
    for word in cnts:
        if cnts[word] > max_cnt:
            res, max_cnt = word, cnts[word]

    return res

[Is Subsequence](https://leetcode.com/problems/is-subsequence/)。给两字串$s$和$t$，判断$s$是否是$t$的子序列。子序列不要求连续。

思路：子序列意味着$s$的所有字符都按顺序出现在$t$中，那么设双指针，当字符相等时，双指针均移动；否则只有$t$的指针移动。

In [ ]:
def isSubsequence(s: str, t: str) -> bool:
    s_idx = t_idx = 0
    n_s, n_t = len(s), len(t)
    while s_idx < n_s and t_idx < n_t:
        if s[s_idx] == t[t_idx]:
            s_idx += 1
        t_idx += 1

    return s_idx == n_s

[Number of Matching Subsequences](https://leetcode.com/problems/number-of-matching-subsequences/)。给一字串$S$与一组字串$words$，计算$words$中有多少字串是$S$的子序列。

思路：判断子序列还是使用双指针法，但是因为测试用例有特殊例子，所以需要考虑优化。设立两个集合保存已经判断过的字串。

In [ ]:
def numMatchingSubseq(S: str, words) -> int:
    res = 0
    passed, not_passed = set(), set()

    def isSub(s, S):
        if s in passed:
            return True
        if s in not_passed:
            return False

        n_s, n_S = len(s), len(S)
        idx_s = idx_S = 0
        while idx_s < n_s and idx_S < n_S:
            if s[idx_s] == S[idx_S]:
                idx_s += 1
            idx_S += 1
        if idx_s == n_s:
            passed.add(s)
            return True
        else:
            not_passed.add(s)
            return False

    for s in words:
        if isSub(s, S):
            res += 1

    return res

[Valid Palindrome](https://leetcode.com/problems/valid-palindrome/)。判断一字串是否构成回文，只考虑数字与字母，并且忽略大小写。

思路：因为只考虑数字字母且忽略大小写，那么设立首尾双指针向中间移动。碰到非数字字母时跳过即可，比较两字符是否相等前需要同意转成小写。

In [ ]:
def isPalindrome(s: str) -> bool:
    n = len(s)
    if n < 2:
        return True

    left, right = 0, n-1
    while left < right:
        while left < right and not s[left].isalnum():
            left += 1
        while left < right and not s[right].isalnum():
            right -= 1

        s_left, s_right = s[left].lower(), s[right].lower()
        if s_left != s_right:
            return False
        else:
            left += 1
            right -= 1

    return True

[Valid Palindrome II](https://leetcode.com/problems/valid-palindrome-ii/)。允许删除一个字符，判定字串能够构成回文。

思路：检测回文的方法就是设立首尾双指针向中间靠近。若碰到两指针不相等，则有两种选择：跳过左指针字符或右指针字符。

In [ ]:
def validPalindrome(s: str) -> bool:
    def valid(s):
        left, right = 0, len(s)-1
        while left < right:
            if s[left] != s[right]:
                return False
            else:
                left += 1
                right -= 1
        return True

    left, right = 0, len(s)-1
    while left < right:
        if s[left] != s[right]:
            return valid(s[left+1:right+1]) or valid(s[left:right])
        else:
            left += 1
            right -= 1

    return True

[Palindromic Substrings](https://leetcode.com/problems/palindromic-substrings/)。给一字符串，找出该字串中有多少个回文子串。不同索引位置的回文即算不同。

思路：判断回文的方法是从中心往两边扩展，但是中心字符的选取却又奇偶两种方式。以奇数形式展开时，中心字符只有一个，即$i==j$；以偶数形式展开时，中心字符有两个，即$i$和$i+1$。

In [ ]:
def countSubstrings(s: str) -> int:
    n = len(s)
    if n < 2:
        return n

    res = 0

    def expand(left, right):
        nonlocal res
        while left >= 0 and right < n and s[left] == s[right]:
            left -= 1
            right += 1
            res += 1

    for idx in range(n):
        expand(idx, idx)
        expand(idx, idx+1)

    return res

[Longest Palindromic Substring](https://leetcode.com/problems/longest-palindromic-substring/)。给一字符串，求出其中最长的回文子串。

思路：要找回文串，从中心开始往两边扩展。注意有奇数和偶数两种情况。

In [ ]:
def longestPalindrome(s: str) -> str:
    n = len(s)
    if n < 2:
        return s

    res = str()

    def expand(left, right):
        nonlocal res
        while left >= 0 and right < n and s[left] == s[right]:
            left -= 1
            right += 1
        if right-left-1 > len(res):
            res = s[left+1:right]

    for idx in range(n):
        expand(idx, idx)    # 奇数扩展
        expand(idx, idx+1)    # 偶数扩展

    return res

[K-diff Pairs in an Array](https://leetcode.com/problems/k-diff-pairs-in-an-array/)。给以正整数数组，求所有差值为$k$的数字对。$(a,b)$和$(b,a)$视为同一对。

思路：排序+双指针。若左右指针的差值小于$k$，则右指针右移；若左右指针的差值大于$k$，则左指针右移。注意避免重复对即可。

In [ ]:
def findPairs(nums, k: int) -> int:
    res = 0
    n = len(nums)
    if k < 0 or n < 2:
        return res

    nums.sort()
    i, j = 0, 1
    while j < n:
        cur_diff = nums[j]-nums[i]
        if cur_diff == k:
            res += 1
            i += 1
            j += 1
            # 避免重复
            while j < n and nums[i] == nums[i-1] and nums[j] == nums[j-1]:
                i += 1
                j += 1
        elif cur_diff < k:
            j += 1
        else:
            i += 1
            if i == j:
                j += 1

    return res

[Max Consecutive Ones](https://leetcode.com/problems/max-consecutive-ones/)。给一$01$数组，求连续$1$的最大长度。

思路：双指针移动即可。

In [ ]:
def findMaxConsecutiveOnes(self, nums: List[int]) -> int:
    res = 0
    start = 0
    n = len(nums)

    while start < n:
        while start < n and nums[start] == 0:
            start += 1

        end = start
        while end < n and nums[end] == 1:
            end += 1

        res = max(res, end-start)
        start = end

    return res

[Maximize Distance to Closest Person](https://leetcode.com/problems/maximize-distance-to-closest-person/)。给一$01$数组表示座位，$0$表示空而$1$表示非空。现求一个距离最近的人最远的座位，返回最远的距离。令相邻距离为$1$。

思路：在原数组中找连续的$0$序列，与相邻人最远的距离应该为$0$序列长度的一半。注意两个边界条件，当$0$序列处于开头或末尾时，可以选择边角座位，这时距离就为$0$序列的长度。

In [ ]:
def maxDistToClosest(self, seats: List[int]) -> int:
    max_zeros = -1
    idx = 0
    n = len(seats)
    start = 0

    while start < n:
        while start < n and seats[start] == 1:
            start += 1

        end = start
        while end < n and seats[end] == 0:
            end += 1

        cur_len = end-start if (start == 0 or end == n) else (end-start+1) >> 1
        if cur_len > max_zeros:
            max_zeros = cur_len
            idx = start
        start = end

    return max_zeros

[Longest Common Prefix](https://leetcode.com/problems/longest-common-prefix/)。给定若干字串，找出它们的最长公共前缀。

思路：易得字串组的最长公共前缀长度不会超过最短字串的长度，所以先求出最短字串的长度，然后逐位比较即可。

In [4]:
def longestCommonPrefix(strs) -> str:
    if not strs:
        return ''
    n = min(list(map(len, strs)))

    res = list()
    base = strs[0][:n]
    for idx in range(n):
        for str in strs[1:]:
            if str[idx] != base[idx]:
                return base[:idx]

    return base

''

[Squares of a Sorted Array](https://leetcode.com/problems/squares-of-a-sorted-array/)。给一有序数组，返回对其平方后的排序数组。

思路：首尾双指针，比较绝对值。在填充返回数组时有一个技巧，填充索引可以直接使用$right-left$。

In [ ]:
def sortedSquares(A):
    n = len(A)
    res = [0]*n
    left, right = 0, n-1

    while left <= right:
        if abs(A[left]) < abs(A[right]):
            res[right-left] = A[right]**2
            right -= 1
        else:
            res[right-left] = A[left]**2
            left += 1

    return res

[Number of Segments in a String](https://leetcode.com/problems/number-of-segments-in-a-string/)。给一字串，求其按空格分割后得到的字串数量。

思路：线性扫描，统计空格字符与非空格字符的边界数量即可，即```s[idx]!=' ' and s[idx-1]==' '```。对首字符特殊处理即可。

In [ ]:
def countSegments(s: str) -> int:
    n = len(s)
    res = 0

    for idx in range(n):
        if s[idx] != ' ':
            if idx == 0 or s[idx-1] == ' ':
                res += 1

    return res

[Find All Anagrams in a String](https://leetcode.com/problems/find-all-anagrams-in-a-string/)。

思路：该题思路其实很简单，就是滑动窗口。但是写起来的逻辑确实不简单。

In [15]:
def findAnagrams(s: str, p: str):
    n, m = len(s), len(p)
    res = list()
    need_cnt=[0]*256
    for ch in p:
        need_cnt[ord(ch)]+=1
        
    for idx in range(m-1):
        if s[idx] in p:
            need_cnt[ord(s[idx])]-=1

    for idx in range(n-m+1):
        if s[idx+m-1] in p:
            need_cnt[ord(s[idx+m-1])]-=1
            
        if sum(need_cnt)==0:
            res.append(idx)
            
        if s[idx] in p:
            need_cnt[ord(s[idx])]+=1

    return res

[0, 4, 5, 6]

[Longest Substring Without Repeating Characters](https://leetcode.com/problems/longest-substring-without-repeating-characters/)。无重复字符的最大子串长度。

思路：滑动窗口+哈希表。哈希表记录每个字符最后出现的位置，当滑动窗口的右指针字符出现过时，有两种情况。一是出现在滑动窗口之外，不用管；而是出现在滑动窗口之内，那么左指针需要移动。

In [27]:
def lengthOfLongestSubstring(s: str) -> int:
    n = len(s)
    left = right = 0
    res = 0
    lookup = [-1]*256

    while right < n:
        if lookup[ord(s[right])] >= left:
            left = lookup[ord(s[right])]+1

        lookup[ord(s[right])] = right
        right += 1
        res = max(res, right-left)

    return res

1

[Summary Ranges](https://leetcode.com/problems/summary-ranges/)。给一有序数组，整理该数组的连续区间。

思路：双指针法。难点在于最后一段需要单独处理。

In [15]:
def summaryRanges(nums):
    n = len(nums)
    res = list()
    start = 0

    while start < n-1:
        end = start+1
        while end < n and nums[end] == nums[end-1]+1:
            end += 1

        if end-start > 1:
            res.append('{}->{}'.format(nums[start], nums[end-1]))
        else:
            res.append(str(nums[start]))
        start = end

    if start == n-1:
        res.append(str(nums[start]))

    return res

['0', '2->4', '6', '8->9']

## Index
索引目前只见于数组题目，最常见的考察内容就是索引与对应位置的值的关系。

给一长度为$n$的数组，其中的数字范围为$[0,n-1]$，判断该数组中是否有重复数字。

思路：若数组中没有重复数字，发现数字恰好和索引是一一对应的。可以使用替换放置的思想，线性扫描数组，若数字与索引不匹配，则尝试将该数字归位，若对应位置上已经有摆放正确的数字，说明有重复数字。

In [65]:
def is_duplicate(arr):
    n = len(arr)
    for idx in range(n):
        while arr[idx] != idx:
            val = arr[idx]
            if arr[val] == arr[idx]:
                return True
            else:
                arr[idx], arr[val] = arr[val], arr[idx]

    return False

[0 0 1 2 3] True
[0 0 0 0 0] True
[0 4 3 2 1] False
[0 2 1 0 4] True
[1 3 0 1 1] True


[Find All Duplicates in an Array](https://leetcode.com/problems/find-all-duplicates-in-an-array/)。给一长度为$n$的正数数组，其中的数字范围为$[1,n]$。求所有重复的元素。

思路：索引法。重复的数字肯定指向同一个位置，那么线性扫描数组，每次将数字(指针)所指向的位置转成负数，若该位置已是负数，说明已有重复指针，加入返回列表即可。

In [2]:
def findDuplicates(nums):
    res = list()

    for num in nums:
        ptr = abs(num)-1

        if nums[ptr] > 0:
            nums[ptr] = -nums[ptr]
        else:
            res.append(abs(num))

    return res

[2, 3]

[Find All Numbers Disappeared in an Array](https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/)。给一长度为$n$的数组，其中数字范围为$[1,n]$，某些数字出现了两次，而某些数字没有出现。找出所有没有出现过的数字。

思路：该题有两个关键点，一是数字范围等于数组长度，二是数字最多出现两次。因此可以使用置换法而不会出现无限循环。

In [3]:
def findDisappearedNumbers(nums):
    n = len(nums)

    for idx in range(n):
        while nums[idx] != (idx+1) and nums[nums[idx]-1] != nums[idx]:
            tmp = nums[nums[idx]-1]
            nums[nums[idx]-1] = nums[idx]
            nums[idx] = tmp

    res = list()
    for idx in range(n):
        if nums[idx] != (idx+1):
            res.append(idx+1)

    return res

[5, 6]

[Maximum Width Ramp](https://leetcode.com/problems/maximum-width-ramp/)。给一数组$A$，定义一个ramp为$(i,j)$，其中$i<j$且$A[i]\le{A[j]}$。求范围最大的ramp的范围。

思路：首先对数组排序，排序后得到的index数组是始终满足$A[i]\le{A[j]}$的。然后只要求$max(j-i)$即可，可参照[该题](https://leetcode.com/problems/best-time-to-buy-and-sell-stock/)。

In [7]:
def maxWidthRamp(A) -> int:
    arr = sorted([(idx, val) for idx, val in enumerate(A)], key=lambda x: x[1])
    res, min_idx = -0x80000000, 0x7FFFFFFF

    for idx, _ in arr:
        min_idx = min(min_idx, idx)
        res = max(res, idx-min_idx)

    return res


maxWidthRamp([0, 1])

1

## In-Place

在涉及数组与字串的题目中，有一部分是不允许新申请空间且要求in-place操作的，这种题目大都是需要利用已有数组的前一部分来充当新数组，并使用**尾指针+工作指针**的双指针的方法来模拟```append```操作。以下几个题都是例子。

[String Compression](https://leetcode.com/problems/string-compression/)。给一字串，将其求地压缩，要求压缩后的字符串长度总是小于等于原字串。返回压缩后字串的截断位置。

思路：基本的字串压缩方法就是把重复字符替换成数字。题目要求压缩字串长度总是小于等于原字串，说明只有重复次数大于$1$时才压缩。就地压缩的话需要维护三个指针，字符的起始指针和结束指针，还有一个写入指针。

In [10]:
def compress(chars) -> int:
    n = len(chars)
    start = write = 0

    while start < n:
        end = start
        while end < n and chars[end] == chars[start]:
            end += 1
        chars[write] = chars[start]
        write += 1

        if end > start+1:
            for digit in str(end-start):
                chars[write] = digit
                write += 1

        start = end

    return write

['a', '2', 'b', '2', 'c', '3']

[Remove Duplicates from Sorted Array](https://leetcode.com/problems/remove-duplicates-from-sorted-array/)。给定一有序数组，就地删掉其中所有冗余的元素，返回非重复元素的个数。

思路：因为是有序数组，所以新出现的非重复元素肯定大于已存在元素。维护一个```last```指针指示已存在的最后一个元素，当工作指针指向的数大于它时，进行覆盖追加。

In [22]:
def removeDuplicates(nums) -> int:
    n = len(nums)
    if n < 2:
        return n

    last, idx = 0, 1
    while idx < n:
        if nums[idx] > nums[last]:
            last += 1
            nums[last] = nums[idx]
        idx += 1

    return last+1

2

[Remove Duplicates from Sorted Array II](https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii/)。给定一有序数组，允许元素出现两次，就地删除冗余元素，返回删除后的数组长度。

思路：相比于上题增加一种情况，若扫描指针的值不大于```last```指针但是允许重复，仍然要做覆盖替换。

In [29]:
def removeDuplicates(nums) -> int:
    n = len(nums)
    if n < 2:
        return n

    last, idx = 0, 1
    tol = 1
    while idx < n:
        if nums[idx] > nums[last]:
            last += 1
            nums[last] = nums[idx]
            tol = 1
        else:
            if tol == 1:
                last += 1
                nums[last] = nums[idx]
                tol -= 1

        idx += 1

    return last+1

5

[Remove Element](https://leetcode.com/problems/remove-element/)。就地删除数组中的所有指定元素，返回删除后的数组长度。

思路：双指针。

In [30]:
def removeElement(nums, val: int) -> int:
    last = 0
    n = len(nums)

    for idx in range(n):
        if nums[idx] != val:
            nums[last] = nums[idx]
            last += 1

    return last

2

[Move Zeroes](https://leetcode.com/problems/move-zeroes/)。 给定一数组，将所有的零移到数组尾部，保持非零元素的相对顺序。

思路：该题即将所有非零元素移动到数组首部，那么使用in-place方法交换零元素与非零元素即可。

In [ ]:
def moveZeroes(nums) -> None:
    n = len(nums)
    last = 0

    for idx in range(n):
        if nums[idx] != 0:
            nums[last], nums[idx] = nums[idx], nums[last]
            last += 1

[Merge Sorted Array](https://leetcode.com/problems/merge-sorted-array/)。给两有序数组```nums1```和```nums2```，两数组中的有效数字个数分别是$m$和$n$，```nums1```的整个长度为$m+n$。将两有序数组合并到```nums1```中。

思路：双尾指针法，从末尾开始填充。

In [ ]:
def merge(nums1, m: int, nums2, n: int) -> None:
    while m > 0 and n > 0:
        if nums1[m-1] > nums2[n-1]:
            nums1[m+n-1] = nums1[m-1]
            m -= 1
        else:
            nums1[m+n-1] = nums2[n-1]
            n -= 1

    if n > 0:    # 当nums2有剩余时才需要处理
        nums1[:n] = nums2[:n]

[Sort Colors](https://leetcode.com/problems/sort-colors/)。数组中有$0$、$1$、$2$三种数字代表三种颜色，对其进行就地排序。

思路：首尾双指针$+$工作指针，首尾指针分别代表$01$和$12$的边界，工作指针线性扫描。遇到$0$则与左边交换，遇到$2$则与右边交换。注意与右边交换时可能交换回一个$0$，需要特殊处理。

In [5]:
def sortColors(nums) -> None:
    left, right = 0, len(nums)-1
    idx = 0

    while idx <= right:
        if nums[idx] == 0:
            nums[left], nums[idx] = nums[idx], nums[left]
            idx += 1
            left += 1
        elif nums[idx] == 2:
            nums[right], nums[idx] = nums[idx], nums[right]
            right -= 1

            while nums[idx] == 0:    # 右边可能交换回0
                nums[left], nums[idx] = nums[idx], nums[left]
                idx += 1
                left += 1
        else:
            idx += 1

[0, 1, 2]